{"uuid": "e34eb2d3-6ce9-4dad-af79-ec90c776f4cc", "children": ["956f6758-d928-45bb-bb29-4e9959f6cddb", "04a07e47-75bc-44d6-966e-81177502bcd2", "92694889-4914-4724-ba5a-b4cae27837ea", "20522ad1-4853-47d5-a56b-4fc02f328e26", "d5736fd8-dfa2-4ecb-b3f4-d0d41239b8e5", "485a2606-db6b-4542-ae05-67cf125084a8", "d69d8f32-1636-4c67-a01a-998d33bf7164", "a0aff3be-fe9e-40dc-be7b-0d7c5ba15f0b", "1426c6fa-5298-42c1-9a3d-dbab164c0928", "408944ed-5b0e-4588-afe4-f61c777b3b41", "f1a01c98-8681-49da-8b7b-4c052d945183", "7789cf03-4f1b-42ca-b4be-e458454a877f", "7ece75d1-c586-447a-bfab-e0280c7c5c70", "1bb8d53c-1bd1-45e8-a36e-f696e780dab8", "3fc40d73-6f68-4247-abd8-03b49d65a8fc", "87a0c3e5-f5f7-4424-b689-1668334031e1", "2910bdcb-3930-40cf-a1a6-d2afbddab150", "592875da-3449-4a56-8499-3e79042324ee", "8f456627-9bef-4e62-8918-57f16c03f2d7", "331e3cb1-7a89-4646-8b0f-60d30bec1eff", "8dc92544-56ae-4096-b4dd-4fc77161fc5b", "b067bbe9-afb5-4b2b-bcbb-a53d910de871"], "befores": [{"name": "tables", "status": "broken", "statusDetails": {"message": "sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation \"areas_id_seq\" does not exist\nLINE 3:  id INTEGER DEFAULT nextval('areas_id_seq'::regclass) NOT NU...\n                                    ^\n\n[SQL: \nCREATE TABLE areas (\n\tid INTEGER DEFAULT nextval('areas_id_seq'::regclass) NOT NULL, \n\tarea VARCHAR NOT NULL, \n\tPRIMARY KEY (id)\n)\n\n]\n(Background on this error at: https://sqlalche.me/e/14/f405)\n", "trace": "  File \"C:\\Users\\Javis\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Users\\Javis\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\Javis\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Javis\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Javis\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Javis\\Worq\\tests\\conftest.py\", line 25, in tables\n    Base.metadata.create_all(bind=engine)\n  File \"C:\\Users\\Javis\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\sqlalchemy\\sql\\schema.py\", line 4930, in create_all\n    bind._run_ddl_visitor(\n  File \"C:\\Users\\Javis\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 3238, in _run_ddl_visitor\n    conn._run_ddl_visitor(visitorcallable, element, **kwargs)\n  File \"C:\\Users\\Javis\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 2221, in _run_ddl_visitor\n    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)\n  File \"C:\\Users\\Javis\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\sqlalchemy\\sql\\visitors.py\", line 524, in traverse_single\n    return meth(obj, **kw)\n           ^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Javis\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\sqlalchemy\\sql\\ddl.py\", line 855, in visit_metadata\n    self.traverse_single(\n  File \"C:\\Users\\Javis\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\sqlalchemy\\sql\\visitors.py\", line 524, in traverse_single\n    return meth(obj, **kw)\n           ^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Javis\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\sqlalchemy\\sql\\ddl.py\", line 899, in visit_table\n    self.connection.execute(\n  File \"C:\\Users\\Javis\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 1385, in execute\n    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Javis\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\sqlalchemy\\sql\\ddl.py\", line 80, in _execute_on_connection\n    return connection._execute_ddl(\n           ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Javis\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 1477, in _execute_ddl\n    ret = self._execute_context(\n          ^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Javis\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 1953, in _execute_context\n    self._handle_dbapi_exception(\n  File \"C:\\Users\\Javis\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 2134, in _handle_dbapi_exception\n    util.raise_(\n  File \"C:\\Users\\Javis\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\sqlalchemy\\util\\compat.py\", line 211, in raise_\n    raise exception\n  File \"C:\\Users\\Javis\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 1910, in _execute_context\n    self.dialect.do_execute(\n  File \"C:\\Users\\Javis\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\sqlalchemy\\engine\\default.py\", line 736, in do_execute\n    cursor.execute(statement, parameters)\n"}, "start": 1750302945892, "stop": 1750302948193}], "start": 1750302945892, "stop": 1750302953328}